apiVersion: v1
kind: PersistentVolume
metadata:
  name: snomed-ui-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /devdrive/edge_snomed_query_ui
    server: 10.0.10.150
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default-nfs
  volumeMode: Filesystem

